CREATE OR REPLACE PROCEDURE PRC_SINCRONIZACION
IS
    CURSOR CR_PRODUCCION_WATERMARK IS
        SELECT * 
        FROM USR_PRODUCCION.WATERMARK;
    --
    CURSOR CR_PRODUCCION_DATOS(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.DATOS 
        WHERE (CODIGO_AGENTE||'-'||NUMERO_DECLARACION)=P_PK;
    --
    CURSOR CR_PRODUCCION_AGENTE(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.AGENTE
        WHERE CODIGO_AGENTE=P_PK;
    --
    CURSOR CR_PRODUCCION_REGIMEN(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.REGIMEN
        WHERE CODIGO_REGIMEN=P_PK;
    --
    CURSOR CR_PRODUCCION_ADUANA(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.ADUANA
        WHERE CODIGO_ADUANA=P_PK;
    --
    CURSOR CR_PRODUCCION_TIPO_OPERACION(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.TIPO_OPERACION
        WHERE CODIGO_TIPO_OPERACION=P_PK;
    --
    CURSOR CR_PRODUCCION_PAIS(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.PAIS
        WHERE CODIGO_PAIS=P_PK;
    --
    CURSOR CR_PRODUCCION_CLIENTE(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.CLIENTE
        WHERE CODIGO_CLIENTE=P_PK;
    --
    CURSOR CR_PRODUCCION_TRANSPORTE(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.MEDIOS_TRANSPORTE
        WHERE CODIGO_TRANSPORTE=P_PK;
    --
    CURSOR CR_PRODUCCION_ALMACENADORA(P_PK USR_PRODUCCION.WATERMARK.PK%TYPE) IS
        SELECT * 
        FROM USR_PRODUCCION.ALMACENADORA
        WHERE CODIGO_ALMACENADORA=P_PK;
    --
    EVENTO_MIGRO 		        USR_PRODUCCION.WATERMARK.MIGRO%TYPE := 'S';
    EVENTO_FECHA_OPERADO        USR_PRODUCCION.WATERMARK.FECHA_OPERADO%TYPE := SYSDATE;
BEGIN
    FOR i IN CR_PRODUCCION_WATERMARK LOOP
        -- SINCRONIZACION DE LA TABLA DATOS
        IF (UPPER(i.TABLA)=UPPER('DATOS') AND UPPER(i.MIGRO)=UPPER('N') AND UPPER(i.OPERACION) IN(UPPER('I'),UPPER('U'))) THEN
            FOR d IN CR_PRODUCCION_DATOS(i.PK) LOOP
                IF (UPPER(i.OPERACION)=UPPER('U')) THEN
                    BEGIN
                        DELETE FROM STG_DATOS WHERE CODIGO_AGENTE=d.CODIGO_AGENTE AND NUMERO_DECLARACION=d.NUMERO_DECLARACION;
                    EXCEPTION WHEN OTHERS THEN
                        RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => STG_DATOS: Ocurrio un error al realizar delete en la tabla STG_DATOS ['||SQLERRM||']');
                        ROLLBACK;
                    END;
                END IF;
                --
                BEGIN
                    INSERT INTO STG_DATOS
                        (CODIGO_AGENTE, NUMERO_DECLARACION, CODIGO_REGIMEN, CODIGO_ADUANA, CODIGO_TIPO_OPERACION, CODIGO_PAIS_ORIGEN, CODIGO_PAIS_VENDEDOR,
                         CLIENTE, CODIGO_TRANSPORTE, TIPO_CAMBIO, FECHA_VALIDACION, FECHA_ADICION, FECHA_PRESENTACION, PESO_TOTAL, VALOR_DOLARES, VALOR_QUETZALES,
                         CODIGO_ALMACENADORA, VALOR_FLETES, VALOR_SEGUROS, VALOR_OTROS_GASTOS)
                    VALUES(d.CODIGO_AGENTE, d.NUMERO_DECLARACION, d.CODIGO_REGIMEN, d.CODIGO_ADUANA, d.CODIGO_TIPO_OPERACION, d.CODIGO_PAIS_ORIGEN, d.CODIGO_PAIS_VENDEDOR,
                         d.CLIENTE, d.CODIGO_TRANSPORTE, d.TIPO_CAMBIO, d.FECHA_VALIDACION, d.FECHA_ADICION, d.FECHA_PRESENTACION, d.PESO_TOTAL, d.VALOR_DOLARES, d.VALOR_QUETZALES,
                         d.CODIGO_ALMACENADORA, d.VALOR_FLETES, d.VALOR_SEGUROS, d.VALOR_OTROS_GASTOS);
                EXCEPTION WHEN OTHERS THEN
                    RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => STG_DATOS: Ocurrio un error al realizar insert en la tabla STG_DATOS ['||SQLERRM||']');
                    ROLLBACK;
                END;
                --
                BEGIN
                    UPDATE USR_PRODUCCION.WATERMARK 
                        SET MIGRO=EVENTO_MIGRO, FECHA_OPERADO=EVENTO_FECHA_OPERADO
                    WHERE UPPER(TABLA)=UPPER(i.TABLA) AND UPPER(OPERACION)=UPPER(i.OPERACION) AND PK=i.PK;
                EXCEPTION WHEN OTHERS THEN
                    RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => WATERMARK: Ocurrio un error al realizar update en la tabla WATERMARK => '||UPPER(i.TABLA)||' ['||SQLERRM||']');
                    ROLLBACK;
                END;
            END LOOP;
        END IF;
        -- SINCRONIZACION DE LA TABLA AGENTE
        IF (UPPER(i.TABLA)=UPPER('AGENTE') AND UPPER(i.MIGRO)=UPPER('N') AND UPPER(i.OPERACION) IN(UPPER('I'),UPPER('U'))) THEN
            FOR a IN CR_PRODUCCION_AGENTE(i.PK) LOOP
                IF (UPPER(i.OPERACION)=UPPER('U')) THEN
                    BEGIN
                        DELETE FROM STG_AGENTE WHERE CODIGO_AGENTE=a.CODIGO_AGENTE;
                    EXCEPTION WHEN OTHERS THEN
                        RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => STG_AGENTE: Ocurrio un error al realizar delete en la tabla STG_AGENTE ['||SQLERRM||']');
                        ROLLBACK;
                    END;
                END IF;
                --
                BEGIN
                    INSERT INTO STG_AGENTE
                        (CODIGO_AGENTE, NOMBRE_AGENTE)
                    VALUES(a.CODIGO_AGENTE, a.NOMBRE_AGENTE);
                EXCEPTION WHEN OTHERS THEN
                    RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => STG_AGENTE: Ocurrio un error al realizar insert en la tabla STG_AGENTE ['||SQLERRM||']');
                    ROLLBACK;
                END;
                --
                BEGIN
                    UPDATE USR_PRODUCCION.WATERMARK 
                        SET MIGRO=EVENTO_MIGRO, FECHA_OPERADO=EVENTO_FECHA_OPERADO
                    WHERE UPPER(TABLA)=UPPER(i.TABLA) AND UPPER(OPERACION)=UPPER(i.OPERACION) AND PK=i.PK;
                EXCEPTION WHEN OTHERS THEN
                    RAISE_APPLICATION_ERROR(-20001, 'PRC_SINCRONIZACION => WATERMARK: Ocurrio un error al realizar update en la tabla WATERMARK => '||UPPER(i.TABLA)||' ['||SQLERRM||']');
                    ROLLBACK;
                END;
            END LOOP;
        END IF;
    END LOOP;
END PRC_SINCRONIZACION;