CREATE OR REPLACE PROCEDURE PRC_DEVUELVE_CORRELATIVOS(
    P_DIMENSION     IN  CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE,
    P_CORRELATIVO   OUT CONTROL_NUMERACION.VALOR%TYPE
)
IS
    EVENTO_TABLA    CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE;
BEGIN
    BEGIN
        SELECT OBJECT_NAME 
            INTO EVENTO_TABLA
        FROM ALL_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE'
        AND OBJECT_NAME = UPPER(P_DIMENSION);
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'PRC_DEVUELVE_CORRELATIVOS => ALL_OBJECTS: Ocurrio un error al realizar la busqueda del objet_name '||UPPER(P_DIMENSION)||' ['||SQLERRM||']');
    END;
    --
    BEGIN
        SELECT VALOR
            INTO P_CORRELATIVO
        FROM CONTROL_NUMERACION
        WHERE NOMBRE_DIMENSION=UPPER(EVENTO_TABLA);
        
        IF P_CORRELATIVO >= 1 THEN
            P_CORRELATIVO := P_CORRELATIVO + 1;
            UPDATE CONTROL_NUMERACION SET VALOR=P_CORRELATIVO WHERE NOMBRE_DIMENSION=UPPER(EVENTO_TABLA); 
        END IF;
    EXCEPTION WHEN OTHERS THEN
        P_CORRELATIVO := 1;
        INSERT INTO CONTROL_NUMERACION(NOMBRE_DIMENSION, VALOR) VALUES(UPPER(EVENTO_TABLA), P_CORRELATIVO);
        RETURN;
    END;
END PRC_DEVUELVE_CORRELATIVOS;