/*=======================================================================================================*/
/* 2. CREACION TRIGGER TABLA 'DIM_AGENTE' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_AGENTE
BEFORE INSERT
ON DIM_AGENTE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_AGENTE';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.AGENTE_KEY := P_KEY;
END TRG_DIM_AGENTE;


/*=======================================================================================================*/
/* 3. CREACION TRIGGER TABLA 'DIM_REGIMEN' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_REGIMEN
BEFORE INSERT
ON DIM_REGIMEN
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_REGIMEN';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.REGIMEN_KEY := P_KEY;
END TRG_DIM_REGIMEN;


/*=======================================================================================================*/
/* 4. CREACION TRIGGER TABLA 'DIM_ADUANA' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_ADUANA
BEFORE INSERT
ON DIM_ADUANA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_ADUANA';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.ADUANA_KEY := P_KEY;
END TRG_DIM_ADUANA;


/*=======================================================================================================*/
/* 5. CREACION TRIGGER TABLA 'DIM_TIPO_OPERACION' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_TIPO_OPERACION
BEFORE INSERT
ON DIM_TIPO_OPERACION
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_TIPO_OPERACION';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.TIPO_OPERACION_KEY := P_KEY;
END TRG_DIM_TIPO_OPERACION;


/*=======================================================================================================*/
/* 6. CREACION TRIGGER TABLA 'DIM_PAIS' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_PAIS
BEFORE INSERT
ON DIM_PAIS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_PAIS';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.PAIS_KEY := P_KEY;
END TRG_DIM_PAIS;


/*=======================================================================================================*/
/* 7. CREACION TRIGGER TABLA 'DIM_CLIENTE' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_CLIENTE
BEFORE INSERT
ON DIM_CLIENTE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_CLIENTE';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.CLIENTE_KEY := P_KEY;
END TRG_DIM_CLIENTE;


/*=======================================================================================================*/
/* 8. CREACION TRIGGER TABLA 'DIM_MEDIOS_TRANSPORTE' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_MEDIOS_TRANSPORTE
BEFORE INSERT
ON DIM_MEDIOS_TRANSPORTE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_MEDIOS_TRANSPORTE';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.MEDIOS_TRANSPORTE_KEY := P_KEY;
END TRG_DIM_MEDIOS_TRANSPORTE;


/*=======================================================================================================*/
/* 9. CREACION TRIGGER TABLA 'DIM_ALMACENADORA' PARA EL CONTROL DE CORRELATIVOS */
CREATE OR REPLACE TRIGGER TRG_DIM_ALMACENADORA
BEFORE INSERT
ON DIM_ALMACENADORA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   P_DIMENSION 	CONTROL_NUMERACION.NOMBRE_DIMENSION%TYPE := 'DIM_ALMACENADORA';
   P_KEY		CONTROL_NUMERACION.VALOR%TYPE;
BEGIN
    PRC_DEVUELVE_CORRELATIVOS(P_DIMENSION, P_KEY);
    :NEW.ALMACENADORA_KEY := P_KEY;
END TRG_DIM_ALMACENADORA;