LOAD DATA 
INFILE 'C:\Users\jarl1\OneDrive\Documentos\ProyectoBBDD2_DanyReyes\FASE_1\4_CargaDatos\ALMACENADORA_1.csv' "str '\r\n'"
TRUNCATE
INTO TABLE ALMACENADORA
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
(
CODIGO_ALMACENADORA CHAR(5),
NOMBRE_ALMACENADORA CHAR(200)
)