LOAD DATA 
INFILE 'C:\Users\jarl1\OneDrive\Documentos\ProyectoBBDD2_DanyReyes\FASE_1\4_CargaDatos\REGIMEN_1.csv' "str '\r\n'"
TRUNCATE
INTO TABLE REGIMEN
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
(
CODIGO_REGIMEN CHAR(2),
NOMBRE_REGIMEN CHAR(200),
PAGO_BANCO CHAR(1)
)