LOAD DATA 
INFILE 'C:\Users\jarl1\OneDrive\Documentos\ProyectoBBDD2_DanyReyes\FASE_1\4_CargaDatos\PAIS_1.csv' "str '\r\n'"
TRUNCATE
INTO TABLE PAIS
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
(
CODIGO_PAIS CHAR(2),
NOMBRE_PAIS CHAR(200)
)