LOAD DATA 
INFILE 'C:\Users\jarl1\OneDrive\Documentos\ProyectoBBDD2_DanyReyes\FASE_1\4_CargaDatos\ADUANA_1.csv' "str '\r\n'"
TRUNCATE
INTO TABLE ADUANA
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
(
CODIGO_ADUANA CHAR(2),
NOMBRE_ADUANA CHAR(200),
TIPO_ADUANA CHAR(1)
)