LOAD DATA 
INFILE 'C:\Users\jarl1\OneDrive\Documentos\ProyectoBBDD2_DanyReyes\FASE_1\4_CargaDatos\AGENTE_1.csv' "str '\r\n'"
TRUNCATE
INTO TABLE AGENTE
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
(
CODIGO_AGENTE CHAR(4),
NOMBRE_AGENTE CHAR(200)
)
