CREATE OR REPLACE PROCEDURE PRC_REPROCESA_DIMENSIONES_QA(
    P_DIMENSION     REPROCESA_DIMENSIONES_QA.NOMBRE_DIMENSION%TYPE,
    P_PARAMETRO     REPROCESA_DIMENSIONES_QA.PARAMETRO%TYPE
)
IS
    EVENTO_TABLA    VALORES_DEFAULT.NOMBRE_METRICA%TYPE;
BEGIN
    BEGIN
        SELECT OBJECT_NAME 
            INTO EVENTO_TABLA
        FROM ALL_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE'
        AND OBJECT_NAME = UPPER(P_DIMENSION);
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'PRC_REPROCESA_DIMENSIONES_QA => ALL_OBJECTS: Ocurrio un error al realizar la busqueda del objet_name '||UPPER(P_DIMENSION)||' ['||SQLERRM||']');
    END;
    --
    BEGIN
        INSERT INTO REPROCESA_DIMENSIONES_QA 
               (NOMBRE_DIMENSION, FECHA, PARAMETRO) 
        VALUES (EVENTO_TABLA, SYSDATE, P_PARAMETRO);
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'PRC_REPROCESA_DIMENSIONES_QA => Error al insertar los datos a la tabla de REPROCESA_DIMENSIONES_QA: ['||SQLERRM||']');
    END;
END PRC_REPROCESA_DIMENSIONES_QA;

CREATE OR REPLACE PROCEDURE PRC_REPROCESA_DIMENSIONES
IS
    CURSOR CR_EVALUA_DIMENSIONES IS
        SELECT 
            a.DIMENSION, SUM(a.CONTADOR) AS CONTADOR
        FROM (
            SELECT 'DIM_AGENTE' AS DIMENSION, COUNT(CODIGO_AGENTE) AS CONTADOR FROM NO_HECHOS WHERE AGENTE_KEY IS NULL
            UNION ALL
            SELECT 'DIM_REGIMEN' AS DIMENSION, COUNT(CODIGO_REGIMEN) AS CONTADOR FROM NO_HECHOS WHERE REGIMEN_KEY IS NULL
            UNION ALL
            SELECT 'DIM_ADUANA' AS DIMENSION, COUNT(CODIGO_ADUANA) AS CONTADOR FROM NO_HECHOS WHERE ADUANA_KEY IS NULL
            UNION ALL
            SELECT 'DIM_TIPO_OPERACION' AS DIMENSION, COUNT(CODIGO_TIPO_OPERACION) AS CONTADOR FROM NO_HECHOS WHERE OPERACION_KEY IS NULL
            UNION ALL
            SELECT 'DIM_PAIS' AS DIMENSION, COUNT(CODIGO_PAIS_ORIGEN) AS CONTADOR FROM NO_HECHOS WHERE PAIS_ORIGEN_KEY IS NULL
            UNION ALL
            SELECT 'DIM_PAIS' AS DIMENSION, COUNT(CODIGO_PAIS_VENDEDOR) AS CONTADOR FROM NO_HECHOS WHERE PAIS_VENDEDOR_KEY IS NULL
            UNION ALL
            SELECT 'DIM_CLIENTE' AS DIMENSION, COUNT(CLIENTE) AS CONTADOR FROM NO_HECHOS WHERE CLIENTE_KEY IS NULL
            UNION ALL
            SELECT 'DIM_MEDIOS_TRANSPORTE' AS DIMENSION, COUNT(CODIGO_TRANSPORTE) AS CONTADOR FROM NO_HECHOS WHERE CODIGO_TRANSPORTE_KEY IS NULL
            UNION ALL
            SELECT 'DIM_ALMACENADORA' AS DIMENSION, COUNT(CODIGO_ALMACENADORA) AS CONTADOR FROM NO_HECHOS WHERE ALMACENADORA_KEY IS NULL
        ) a
        GROUP BY a.DIMENSION;
BEGIN
    FOR i IN CR_EVALUA_DIMENSIONES LOOP
        IF i.DIMENSION = 'DIM_AGENTE' AND i.CONTADOR != 0 THEN
            PRC_DIM_AGENTE(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_REGIMEN' AND i.CONTADOR != 0 THEN
            PRC_DIM_REGIMEN(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_ADUANA' AND i.CONTADOR != 0 THEN
            PRC_DIM_ADUANA(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_TIPO_OPERACION' AND i.CONTADOR != 0 THEN
            PRC_DIM_TIPO_OPERACION(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_PAIS' AND i.CONTADOR != 0 THEN
            PRC_DIM_PAIS(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_CLIENTE' AND i.CONTADOR != 0 THEN
            PRC_DIM_CLIENTE(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_MEDIOS_TRANSPORTE' AND i.CONTADOR != 0 THEN
            PRC_DIM_MEDIOS_TRANSPORTE(2);
        END IF;
        --
        IF i.DIMENSION = 'DIM_ALMACENADORA' AND i.CONTADOR != 0 THEN
            PRC_DIM_ALMACENADORA(2);
        END IF;
    END LOOP;
END;