CREATE OR REPLACE FUNCTION FNC_DEVUELVE_VALOR_DEFAULT(
    P_METRICA       VALORES_DEFAULT.NOMBRE_METRICA%TYPE,
    P_VALOR     OUT VALORES_DEFAULT.VALOR%TYPE
)
    RETURN NUMBER
IS
    EVENTO_TABLA    VALORES_DEFAULT.NOMBRE_METRICA%TYPE;
BEGIN
    BEGIN
        SELECT OBJECT_NAME 
            INTO EVENTO_TABLA
        FROM ALL_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE'
        AND OBJECT_NAME = UPPER('VALORES_DEFAULT');
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FNC_DEVUELVE_VALOR_DEFAULT => ALL_OBJECTS: Ocurrio un error al realizar la busqueda del objet_name '||UPPER('VALORES_DEFAULT')||' ['||SQLERRM||']');
    END;
    --
    BEGIN
        SELECT VALOR
            INTO P_VALOR
        FROM VALORES_DEFAULT
        WHERE UPPER(NOMBRE_METRICA) = UPPER(P_METRICA);
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FNC_DEVUELVE_VALOR_DEFAULT => Ocurrio un error al realizar la busqueda del valor de la metrica '||UPPER(P_METRICA)||' ['||SQLERRM||']');
    END;
    
    RETURN P_VALOR;
END FNC_DEVUELVE_VALOR_DEFAULT;