GRANT SELECT ON DATOS TO USR_STAGE;
GRANT SELECT ON AGENTE TO USR_STAGE;
GRANT SELECT ON REGIMEN TO USR_STAGE;
GRANT SELECT ON ADUANA TO USR_STAGE;
GRANT SELECT ON TIPO_OPERACION TO USR_STAGE;
GRANT SELECT ON PAIS TO USR_STAGE;
GRANT SELECT ON CLIENTE TO USR_STAGE;
GRANT SELECT ON MEDIOS_TRANSPORTE TO USR_STAGE;
GRANT SELECT ON ALMACENADORA TO USR_STAGE;

GRANT SELECT, UPDATE ON WATERMARK TO USR_STAGE;